# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-ast
      - id: check-added-large-files
      - id: debug-statements
      - id: name-tests-test
        args: [ "--pytest-test-first" ]
        exclude: "fixtures.py"
      - id: requirements-txt-fixer

  - repo: https://github.com/psf/black
    # Black
    rev: '24.3.0'
    hooks:
      - id: black

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff
    rev: 'v0.3.3'
    hooks:
      - id: ruff

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/jendrikseipp/vulture
    rev: 'v2.11'  # or any later Vulture version
    hooks:
      - id: vulture
