[tool.black]
line-length = 120

[tool.codespell]
skip = './.git/,./venv,*/htmlcov/*,./codespell_ignore.txt,requirements.txt'
quiet-level = 3
ignore-words = 'codespell_ignore.txt'

[tool.isort]
profile = "black"


[tool.ruff]
target-version = "py310"
line-length = 120
extend-exclude = [
    "__init__.py"
]

[tool.vulture]
min_confidence = 80
sort_by_size = true
verbose = false
paths = ["pyspold"]
